# Generated by Django 3.0.4 on 2021-07-20 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='cid',
            field=models.CharField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
