# Generated by Django 3.0.4 on 2021-08-05 07:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0003_notarrange'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='campus',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app01.Campus'),
        ),
    ]
